server:
  port: 8763
spring:
  zipkin:
    base-url: http://localhost:9411
    readTimeout:  6000
  application:
    name: service-hello

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

